In [1]:
def add(a,b):
  return a+b

In [2]:
x = 10
y= 20
res = add (x,y)
print("sum=",res)

sum= 30


In [4]:
def welcome():
 print("welcome to Python Lab")
welcome()

welcome to Python Lab


In [6]:
def sq(n):
  return n*n
print(sq(5))

25


In [9]:
# Make two array user input using numpy
import numpy as np
n = int(input("How many Number?"))
number = [ ]
for i in range(n):
  x = int(input("Enter Number:"))
  number.append(x)
  arr = np.array(number)
print("Numpy Array:", arr)
print("Array type:", type(arr))
print("NUmpy Array type", arr.dtype)
print("Numpy Array dimension", arr.ndim)
print("Numpy Array shape", arr.shape)
print("Numpy Array size", arr.size)

How many Number?4
Enter Number:1
Enter Number:2
Enter Number:3
Enter Number:4
Numpy Array: [1 2 3 4]
Array type: <class 'numpy.ndarray'>
NUmpy Array type int64
Numpy Array dimension 1
Numpy Array shape (4,)
Numpy Array size 4


In [15]:
def create_array(n):
  number = []
  for i in range(n):
   x = int(input("Enter Number:"))
   number.append(x)
  return np.array(number)

In [16]:
n= int(input("How many Number?"))
arr = create_array(n)
print("Numpy Array:", arr)
print("Array type:", type(arr))
print("Numpy Array type", arr.dtype)
print("Numpy Array dimension", arr.ndim)
print("Numpy Array shape", arr.shape)
print("Numpy Array size", arr.size)

How many Number?4
Enter Number:1
Enter Number:2
Enter Number:3
Enter Number:4
Numpy Array: [1 2 3 4]
Array type: <class 'numpy.ndarray'>
Numpy Array type int64
Numpy Array dimension 1
Numpy Array shape (4,)
Numpy Array size 4


## Default Arguments

In [17]:
def printInfo(name,age):
  print("Name:",name)
  print("Age:",age)

In [18]:
def printInfo(name, age=21):
  print("Name:", name)
  print("Age:", age)



In [21]:
printInfo("Yogesh",25)
printInfo ("Varun")


Name: Yogesh
Age: 25
Name: Varun
Age: 21


## Required Argument

In [22]:
def printInfo(name, age):
  print("Name:", name)
  print("Age:", age)


In [24]:
printInfo("Yogesh",25)


Name: Yogesh
Age: 25


## Keyword Arguments

In [25]:
def printInfo(name, age):
  print("Name:", name)
  print("Age:", age)


In [26]:
printInfo(age=25, name="Yogesh")

Name: Yogesh
Age: 25


## Variable Length  (*argument

---



In [28]:
def add (a,b):
 print(a+b)

In [31]:
def add(*num):
  total = 0
  for n in num:
    total += n
  print(total)

In [32]:
add(10, 20)
add(10, 20, 30, 40)

30
100


## Variable length argument (**kwargs)

In [39]:
def student(**details):
 print(details)
student(name = "Yogesh", age = 25, course ="python")

{'name': 'Yogesh', 'age': 25, 'course': 'python'}


In [42]:
def calculate(a, b):
  return a+b, a-b, a*b

s, d, m = calculate(10, 5)
print("Sum",s)
print("Difference",d)
print("Multiplication",m)

Sum 15
Difference 5
Multiplication 50


## Reshaping Array

In [43]:
data = np.arange(1,13)
a= data.reshape(3,4)
b= data.reshape(4,3)
c= data.reshape(2,-1)
print(f'1D:{data}')
print(f'3x4:\n{a}')
print(f'4x3:\n{b}')
print(f'2xinfer:\n{c}')

print(f'A shape:\n{a.shape}')
print(f'B shape:\n{b.shape}')
print(f'C shape:\n{c.shape}')

1D:[ 1  2  3  4  5  6  7  8  9 10 11 12]
3x4:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
4x3:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2xinfer:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
A shape:
(3, 4)
B shape:
(4, 3)
C shape:
(2, 6)


Make a function to take input from user and reshape numpy array into 6x2 matrix 3x-1 matrix and 5x-1 matrix. If error comes please explain the error

In [44]:
def reshape_user_input():
    try:
        arr = np.array([float(x) for x in input("Numbers: ").split()])
    except ValueError:
        print("Error: Invalid numbers input.")
        return

    n = arr.size
    for shape in [(6, 2), (3, -1), (5, -1)]:
        try:
            print(f"Shape {shape}:\n{arr.reshape(shape)}\n")
        except ValueError:
            req = shape[0] if shape[1] == -1 else shape[0] * shape[1]
            if shape[1] == -1:
                print(f"Error for {shape}: Total elements ({n}) must be divisible by {req}.\n")
            else:
                print(f"Error for {shape}: Requires exactly {req} elements, got {n}.\n")

reshape_user_input()

Numbers: 4
Error for (6, 2): Requires exactly 12 elements, got 1.

Error for (3, -1): Total elements (1) must be divisible by 3.

Error for (5, -1): Total elements (1) must be divisible by 5.



## flatten() and ravel()

In [46]:
data = np.array([[[1,2,3],[4,5,6]]])
print("Data shape:",data.ndim)
flat1 = data.flatten()
print("Data shape:",flat1.ndim)
flat2 = data.ravel()
print("Data shape:",flat2.ndim)

Data shape: 3
Data shape: 1
Data shape: 1


# np.concatenate()
#np.vstack()
#np.hstack()

In [47]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(f'concatenate:{np.concatenate((a,b))}')
print(f'vstack:\n{np.vstack((a,b))}')
print(f'hstack:\n{np.hstack((a,b))}')

concatenate:[1 2 3 4 5 6]
vstack:
[[1 2 3]
 [4 5 6]]
hstack:
[1 2 3 4 5 6]


In [50]:
data = np.array([10,20,30,40,50])
result = []
for x in data:
    result.append(x*2)
print(f'loop array:,{result}')

loop array:,[np.int64(20), np.int64(40), np.int64(60), np.int64(80), np.int64(100)]


In [51]:
vec_result = data*2
print(f'Vec array: {vec_result}')

Vec array: [ 20  40  60  80 100]


In [53]:
a = np.array([10,20,30,])
b = np.array([2,4,5])
print("Addition",a+b)
print("Subtraction",a-b)
print("Multiplication",a*b)
print("Division",a/b)
print("Modulus",a%b)

Addition [12 24 35]
Subtraction [ 8 16 25]
Multiplication [ 20  80 150]
Division [5. 5. 6.]
Modulus [0 0 0]


In [54]:
marks = np.array([50,60,70,80,90])
print(f'Add 5:{marks+5}')
print(f'Sub 10:{marks-10}')
print(f'Double:{marks*2}')
print(f'Half:{marks/2}')

Add 5:[55 65 75 85 95]
Sub 10:[40 50 60 70 80]
Double:[100 120 140 160 180]
Half:[25. 30. 35. 40. 45.]


In [55]:
print(f'sqrt:{np.sqrt(marks)}')


sqrt:[7.07106781 7.74596669 8.36660027 8.94427191 9.48683298]


In [56]:
print(f'square:{np.square(marks)}')


square:[2500 3600 4900 6400 8100]


## Broadcasting

In [58]:
arr = np.array([1,2,3])
res = arr+1
print(res)

[2 3 4]


In [59]:
a = np.array([2,4,6])
b = np.array([[3,5,7],[7,9,11]])
res = a+b
print(res)

[[ 5  9 13]
 [ 9 13 17]]


## Broadcasting in conditional operation

In [61]:
a = np.array([12,34,65,72,80])
b=np.array(["Adult","Minor"])
res=np.where(a>=18,b[0],b[1])
print(res)

['Minor' 'Adult' 'Adult' 'Adult' 'Adult']


## Broadcasting for Matrix Multiplication

In [62]:
m = np.array([[1,2],[3,4]])
v= np.array([10,20])
res= v*m
print(res)

[[10 40]
 [30 80]]
