In [5]:
num=int(input("enter an integer"))
print(type(num))

enter an integer5
<class 'int'>


In [6]:
for i in range(1,11):
  print(f'{num} x {i} = {num * i}')

5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50


In [7]:
a= float(input("Enter first number"))
b= float(input("Enter second number"))
print(f'The sum of {a} and {b} is {a+b}')
print(f'Sustraction of {a} and {b} is {a-b}')
print(f'Multiplication of {a} and {b} is {a*b}')
print(f'Division of {a} and {b} is {a/b}')
print(f'Floor division of {a} and {b} is {a//b}')
print(f'Modulus of {a} and {b} is {a%b}')
print(f'Exponent of {a} and {b} is {a**b}')

Enter first number17.9
Enter second number4.5
The sum of 17.9 and 4.5 is 22.4
Sustraction of 17.9 and 4.5 is 13.399999999999999
Multiplication of 17.9 and 4.5 is 80.55
Division of 17.9 and 4.5 is 3.9777777777777774
Floor division of 17.9 and 4.5 is 3.0
Modulus of 17.9 and 4.5 is 4.399999999999999
Exponent of 17.9 and 4.5 is 434348.8134104658


In [9]:
nums=[12,14,19,10,20]
tot= 0
for x in nums:
  tot=tot+x
print(f'The total is {tot}')
avg = tot/len(nums)
print(f'The average is {avg}')

The total is 75
The average is 15.0


In [10]:
import numpy as np


In [11]:
marks = np.array([72,65,81,54,90])
print("Array:", marks)
print("type:",type(marks))


Array: [72 65 81 54 90]
type: <class 'numpy.ndarray'>


In [12]:
marks = np.array([72.0,65,81,54,90])
print("Array:", marks)
print("type:",type(marks))

Array: [72. 65. 81. 54. 90.]
type: <class 'numpy.ndarray'>


In [14]:
marks = np.array([72,True,81,54,90])
print("Array:", marks)
print("type:",type(marks))

Array: [72  1 81 54 90]
type: <class 'numpy.ndarray'>


In [15]:
marks = np.array([72,65,False,54,90])
print("Array:", marks)
print("type:",type(marks))

Array: [72 65  0 54 90]
type: <class 'numpy.ndarray'>


In [19]:
a2d = np.array([[1,2,3],[4,5,6]])
print(f'Array: {a2d}')
print(f'Type:{a2d.dtype}')
print(f'Dimension: {a2d.ndim}')
print(f'shape: {a2d.shape}')
print(f'size: {a2d.size}')

Array: [[1 2 3]
 [4 5 6]]
Type:int64
Dimension: 2
shape: (2, 3)
size: 6


In [20]:
a0d = np.array(46)
print(f'Array: {a0d}')
print(f'Type:{a0d.dtype}')
print(f'Dimension: {a0d.ndim}')
print(f'shape: {a0d.shape}')
print(f'size: {a0d.size}')

Array: 46
Type:int64
Dimension: 0
shape: ()
size: 1


In [22]:
a3d = np.array([[[1,2,3], [4,5,6], [14,15,16]]])
print(f'Array: {a3d}')
print(f'Type:{a3d.dtype}')
print(f'Dimension: {a3d.ndim}')
print(f'shape: {a3d.shape}')
print(f'size: {a3d.size}')

Array: [[[ 1  2  3]
  [ 4  5  6]
  [14 15 16]]]
Type:int64
Dimension: 3
shape: (1, 3, 3)
size: 9


In [23]:
import numpy as np

array_3d = np.zeros((2, 3, 3))

print("Array:")
print(array_3d)

print("\nDimension (ndim):", array_3d.ndim)
print("Shape:", array_3d.shape)

Array:
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]

Dimension (ndim): 3
Shape: (2, 3, 3)


In [24]:
print(f'a1d[0]')

a1d[0]


In [26]:
a1d = np.array([10, 20, 30, 40, 50])
a1d[2]=23
print(a1d)

[10 20 23 40 50]


In [28]:
print(f'Array:{a2d}')
print(f'row1,col2: {a2d[0,1]}')
print(f'row2,col3: {a2d[1,2]}')

Array:[[1 2 3]
 [4 5 6]]
row1,col2: 2
row2,col3: 6


In [30]:
print(f'Array:{a2d}')
print(f'row1,col2: {a2d[0,1]}')
print(f'row2,col3: {a2d[1,2]}')
print('Second row:{a2d[1,:]}')
print('Second column:{a2d[:,1]}')
print(f'Third column:{a2d[:,2]}')

Array:[[1 2 3]
 [4 5 6]]
row1,col2: 2
row2,col3: 6
Second row:{a2d[1,:]}
Second column:{a2d[:,1]}
Third column:[3 6]


In [31]:
print(f'Array:{a3d}')

Array:[[[ 1  2  3]
  [ 4  5  6]
  [14 15 16]]]


In [33]:
print(f'Array:{a3d}')
print(f'row1,col2: {a3d[0,1,1]}')
print(f'row2,col3: {a3d[0,2,2]}')

Array:[[[ 1  2  3]
  [ 4  5  6]
  [14 15 16]]]
row1,col2: 5
row2,col3: 16


In [34]:
print(f'Array:{a1d}')

Array:[10 20 23 40 50]


In [35]:
print(f'First four elements:{a1d[:4]}')
print(f'First 3 elements:{a1d[:3]}')
print(f'Last three elements:{a1d[3:]}')
print(f'Last two elements:{a1d[-2:]}')
print(f'Reverse:{a1d[::-1]}')
print(f'Middle:{a1d[2:6]}')
print(f'Every second value:{a1d[::2]}')

First four elements:[10 20 23 40]
First 3 elements:[10 20 23]
Last three elements:[40 50]
Last two elements:[40 50]
Reverse:[50 40 23 20 10]
Middle:[23 40 50]
Every second value:[10 23 50]


Write a programme to take 12 element in arry and rev only the first six values

In [42]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a[:6]=a[5::-1]
print(a)

[ 6  5  4  3  2  1  7  8  9 10 11 12]


In [43]:
ze= np.zeros(5)
print(ze)
print(f'type:{ze.dtype}')
print(f'Dimension: {ze.ndim}')
print(f'shape: {ze.shape}')
print(f'size: {ze.size}')

[0. 0. 0. 0. 0.]
type:float64
Dimension: 1
shape: (5,)
size: 5


In [48]:
# all element one rakhne h
one= np.ones((2,3))
print(one)
print(f'type:{one.dtype}')
print(f'Dimension: {one.ndim}')
print(f'shape: {one.shape}')
print(f'size: {one.size}')


[[1. 1. 1.]
 [1. 1. 1.]]
type:float64
Dimension: 2
shape: (2, 3)
size: 6


In [49]:
full = np.full((2,3),7)
print(full)
print(f'type:{full.dtype}')
print(f'Dimension: {full.ndim}')
print(f'shape: {full.shape}')
print(f'size: {full.size}')

[[7 7 7]
 [7 7 7]]
type:int64
Dimension: 2
shape: (2, 3)
size: 6


In [52]:
one = np.ones((2, 3), dtype=int)
print(one)
print(f'type:{one.dtype}')
print(f'Dimension: {one.ndim}')
print(f'shape: {one.shape}')
print(f'size: {one.size}')

[[1 1 1]
 [1 1 1]]
type:int64
Dimension: 2
shape: (2, 3)
size: 6


create 4x2 matrix fill with 100

In [53]:
matrix = np.full((4,2),100)
print(matrix)

[[100 100]
 [100 100]
 [100 100]
 [100 100]]


#Generating sequence with arange() and linspace()

In [54]:
a=np.arange(0,10,2)
print(a)

[0 2 4 6 8]


In [56]:
b=np.linspace(0,10,6)
print(b)

[ 0.  2.  4.  6.  8. 10.]


In [57]:
b=np.linspace(0,1,6)
print(b)

[0.  0.2 0.4 0.6 0.8 1. ]


In [58]:
b=np.linspace(1,20,6)
print(b)

[ 1.   4.8  8.6 12.4 16.2 20. ]


#Random number generation

In [59]:
print(f'Random decimal:{np.random.random(5)}')


Random decimal:[0.62970849 0.51294504 0.58642059 0.52792489 0.89462267]


In [60]:
#Control random number .seed(any number)
np.random.seed(42)
print(f'Random decimal:{np.random.random(5)}')

Random decimal:[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


In [65]:
print(f'Random Integer:{np.random.randint(1,11, size=(3,3))}')

Random Integer:[[3 7 8]
 [5 4 8]
 [8 3 6]]


In [66]:
print(f'{np.random.rand(2,3)}')

[[5.64115790e-02 7.21998772e-01 9.38552709e-01]
 [7.78765841e-04 9.92211559e-01 6.17481510e-01]]
